In [ ]:
!pip install tiny_tradier

In [1]:
from tradier import Tradier
tiny = Tradier()

In [2]:
response = tiny.account.get_profile(paper=False).json()
#response

In [3]:
#response = tiny.account.get_positions(account_id="VA3716401",paper=True).json()
response = tiny.account.get_positions(paper=False).json()
response

{'positions': 'null'}

In [5]:
response = tiny.market_data.get_quotes(symbols="AAPL,MSFT,NVDA,SPY").json()
response

{'quotes': {'quote': [{'symbol': 'AAPL',
    'description': 'Apple Inc',
    'exch': 'Q',
    'type': 'stock',
    'last': 181.56,
    'change': -0.75,
    'volume': 53630268,
    'open': 181.79,
    'high': 182.43,
    'low': 180.0,
    'close': 181.56,
    'bid': 181.6,
    'ask': 181.67,
    'change_percentage': -0.42,
    'average_volume': 53525718,
    'last_volume': 5166854,
    'trade_date': 1708462800513,
    'prevclose': 182.31,
    'week_52_high': 199.62,
    'week_52_low': 143.9,
    'bidsize': 1,
    'bidexch': 'P',
    'bid_date': 1708472982000,
    'asksize': 1,
    'askexch': 'P',
    'ask_date': 1708472984000,
    'root_symbols': 'AAPL'},
   {'symbol': 'MSFT',
    'description': 'Microsoft Corp',
    'exch': 'Q',
    'type': 'stock',
    'last': 402.79,
    'change': -1.27,
    'volume': 24291004,
    'open': 403.24,
    'high': 404.49,
    'low': 398.01,
    'close': 402.79,
    'bid': 401.06,
    'ask': 401.5,
    'change_percentage': -0.32,
    'average_volume': 29453247,
    'last_volume': 3039892,
    'trade_date': 1708462800370,
    'prevclose': 404.06,
    'week_52_high': 420.82,
    'week_52_low': 245.61,
    'bidsize': 5,
    'bidexch': 'Q',
    'bid_date': 1708472917000,
    'asksize': 2,
    'askexch': 'P',
    'ask_date': 1708472887000,
    'root_symbols': 'MSFT'},
   {'symbol': 'NVDA',
    'description': 'NVIDIA Corp',
    'exch': 'Q',
    'type': 'stock',
    'last': 694.52,
    'change': -31.61,
    'volume': 70256255,
    'open': 719.47,
    'high': 719.56,
    'low': 677.34,
    'close': 694.52,
    'bid': 683.99,
    'ask': 684.23,
    'change_percentage': -4.36,
    'average_volume': 9573901,
    'last_volume': 1664241,
    'trade_date': 1708462800314,
    'prevclose': 726.13,
    'week_52_high': 746.11,
    'week_52_low': 204.21,
    'bidsize': 5,
    'bidexch': 'Q',
    'bid_date': 1708472984000,
    'asksize': 1,
    'askexch': 'C',
    'ask_date': 1708472919000,
    'root_symbols': 'NVDA'},
   {'symbol': 'SPY',
    'description': 'SPDR S&P 500',
    'exch': 'P',
    'type': 'etf',
    'last': 496.76,
    'change': -2.75,
    'volume': 71708402,
    'open': 497.72,
    'high': 498.41,
    'low': 494.45,
    'close': 496.76,
    'bid': 496.3,
    'ask': 496.36,
    'change_percentage': -0.56,
    'average_volume': 77045157,
    'last_volume': 0,
    'trade_date': 1708471800000,
    'prevclose': 499.51,
    'week_52_high': 503.5,
    'week_52_low': 380.65,
    'bidsize': 5,
    'bidexch': 'Q',
    'bid_date': 1708472975000,
    'asksize': 5,
    'askexch': 'Q',
    'ask_date': 1708472975000,
    'root_symbols': 'SPY'}]}}

In [3]:
response = tiny.market_data.get_company_dividends(symbols="MSFT,MO,KMI")
response

In [10]:
import pandas as pd
df_div = pd.DataFrame()
response.json()
for r in response.json():
    for result in r['results']:
        df_temp = pd.DataFrame(result['tables']['cash_dividends'])
        df_temp['symbol'] = r['request']
        df_temp['type'] = result['type']
        df_div = pd.concat([df_div,df_temp],ignore_index=True)
df_div.shape

(287, 12)

In [11]:
df_div.head()

,share_class_id,dividend_type,ex_date,cash_amount,currency_i_d,declaration_date,frequency,pay_date,record_date,symbol,type,id
0,0P000003MH,CD,2024-02-14,0.75,USD,2023-11-28,4.0,2024-03-14,2024-02-15,MSFT,Stock,0P000003MH
1,0P000003MH,CD,2023-11-15,0.75,USD,2023-09-19,4.0,2023-12-14,2023-11-16,MSFT,Stock,0P000003MH
2,0P000003MH,CD,2023-08-16,0.68,USD,2023-06-13,4.0,2023-09-14,2023-08-17,MSFT,Stock,0P000003MH
3,0P000003MH,CD,2023-05-17,0.68,USD,2023-03-14,4.0,2023-06-08,2023-05-18,MSFT,Stock,0P000003MH
4,0P000003MH,CD,2023-02-15,0.68,USD,2022-11-29,4.0,2023-03-09,2023-02-16,MSFT,Stock,0P000003MH

In [17]:
df_div.loc[df_div['ex_date']>"2023-11-02"].sort_values(['symbol','ex_date'])

,share_class_id,dividend_type,ex_date,cash_amount,currency_i_d,declaration_date,frequency,pay_date,record_date,symbol,type,id
235,0P0000SDEF,CD,2024-01-30,0.2825,USD,2024-01-17,4.0,2024-02-15,2024-01-31,KMI,Stock,0P0000SDEF
82,0P000000AV,CD,2023-12-20,0.9800,USD,2023-12-06,4.0,2024-01-10,2023-12-21,MO,Stock,0P000000AV
1,0P000003MH,CD,2023-11-15,0.7500,USD,2023-09-19,4.0,2023-12-14,2023-11-16,MSFT,Stock,0P000003MH
0,0P000003MH,CD,2024-02-14,0.7500,USD,2023-11-28,4.0,2024-03-14,2024-02-15,MSFT,Stock,0P000003MH